#ifndef CHOCOLATE_SMART_HOME_MICROCONTROLLERS_H
#define CHOCOLATE_SMART_HOME_MICROCONTROLLERS_H

// Version format: xxyyzz == "xx.yy.zz"
#define CHOCOLATE_SMART_HOME_MICROCONTROLLERS_VERSION 10000
#define CHOCOLATE_SMART_HOME_MICROCONTROLLERS_VERSION_STRING "1.0.0"

namespace OnOff {
#include "on_off/on_off.h"
}

#endif
