# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := on_off_test
ARDUINO_LIBS := AUnit chocolate-smart-home-microcontrollers
include ../../../EpoxyDuino/EpoxyDuino.mk
